version: 2

models:
  - name: stg_orders
    description: "Staged and cleaned payment transactions (orders) for the Utility Marketplace Platform."
    columns:
      - name: order_id
        description: "Unique identifier for each payment transaction."
        tests:
          - unique
          - not_null
      - name: order_status
        description: "Current status of the payment transaction."
        tests:
          - accepted_values:
              arguments:
                values: ['DELIVERED', 'SHIPPED', 'CANCELED', 'UNAVAILABLE', 'INVOICED', 'PROCESSING', 'CREATED', 'APPROVED']

  - name: stg_customers
    description: "Staged and cleaned account holder (customer) data."
    columns:
      - name: customer_id
        description: "Unique identifier for each account holder."
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Deduplicated unique identifier for an account holder across multiple orders."

  - name: stg_products
    description: "Staged and cleaned utility service types (products)."
    columns:
      - name: product_id
        description: "Unique identifier for each utility service type."
        tests:
          - unique
          - not_null

  - name: stg_payments
    description: "Staged and cleaned payment method records per transaction."
    columns:
      - name: order_id
        description: "Foreign key to the associated payment transaction."
        tests:
          - not_null
      - name: payment_type
        description: "Method used for payment (e.g., CREDIT_CARD, BOLETO, VOUCHER, DEBIT_CARD)."
      - name: payment_installments
        description: "Number of installments for the payment. 1 = single payment."
      - name: payment_value
        description: "Payment amount in BRL for this payment sequence."

  - name: stg_order_items
    description: "Staged and cleaned line items per transaction (utility service charges)."
    columns:
      - name: order_id
        description: "Foreign key to the associated payment transaction."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to the utility service type."
        tests:
          - not_null
  - name: stg_brl_usd_exchange_rate
    description: "Daily BRL to USD exchange rates used for currency normalisation."
    columns:
      - name: rate_date
        description: "Date of the exchange rate."
        tests:
          - not_null
          - unique
      - name: exchange_rate_to_usd
        description: "Conversion rate from BRL to USD for the given date."
        tests:
          - not_null