version: 2

sources:
  - name: raw
    description: "Raw data sources for the e-commerce platform loaded from seeds."
    schema: main_raw
    tables:
      - name: raw_orders
        description: "Raw orders data from the e-commerce platform."
        columns:
          - name: order_id
            description: "Unique identifier for each order."
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Identifier for the customer who placed the order."
          - name: order_purchase_timestamp
            description: "Timestamp when the order was placed."

      - name: raw_customers
        description: "Raw customers data from the e-commerce platform."
        columns:
          - name: customer_id
            description: "Unique identifier for each customer."
            tests:
              - unique
              - not_null
          - name: customer_unique_id
            description: "Unique identifier for each customer across all orders."

      - name: raw_products
        description: "Raw products data from the e-commerce platform."
        columns:
          - name: product_id
            description: "Unique identifier for each product."
            tests:
              - unique
              - not_null

      - name: raw_payments
        description: "Raw payments data from the e-commerce platform."
        columns:
          - name: order_id
            description: "Identifier for the order associated with the payment."
      - name: raw_order_items
        description: "Raw order items data from the e-commerce platform."
        columns:
          - name: order_id
            description: "Identifier for the order associated with the item."
          - name: product_id
            description: "Identifier for the product associated with the item."
      - name: raw_brl_usd_exchange_rate
        description: "Daily FX rates BRL to USD."
        columns:
          - name: rate_date
            tests:
              - not_null
          - name: exchange_rate_to_usd
            tests:
              - not_null
          
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: _loaded_at