version: 2

sources:
  - name: raw
    description: "Raw data sources for the Utility Marketplace Platform loaded from seeds."
    schema: main_raw
    tables:
      - name: raw_orders
        description: "Raw payment transaction records."
        # Data Quality Check 3: Freshness
        loaded_at_field: order_purchase_timestamp
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
          - name: order_id
            description: "Unique identifier for each payment transaction."
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "FK to the account holder who initiated the transaction."
          - name: order_purchase_timestamp
            description: "Timestamp when the transaction was initiated."
            tests: 
              - not_null

      - name: raw_customers
        description: "Raw account holder records."
        columns:
          - name: customer_id
            description: "Unique identifier for each account holder."
            tests:
              - unique
              - not_null
          - name: customer_unique_id
            description: "Deduplicated account holder ID across multiple transactions."
            tests:
              - not_null

      - name: raw_products
        description: "Raw utility service type catalogue."
        columns:
          - name: product_id
            description: "Unique identifier for each utility service type."
            tests:
              - unique
              - not_null

      - name: raw_payments
        description: "Raw payment method records per transaction."
        columns:
          - name: order_id
            description: "FK to the associated payment transaction."
            tests:
              - not_null

      - name: raw_order_items
        description: "Raw line items (charges) per transaction."
        columns:
          - name: order_id
            description: "FK to the associated payment transaction."
            tests:
              - not_null
          - name: product_id
            description: "FK to the utility service type."
            tests:
              - not_null

      - name: raw_brl_usd_exchange_rate
        description: "Daily BRL to USD exchange rates."
        columns:
          - name: rate_date
            tests:
              - not_null
              - unique
          - name: exchange_rate_to_usd
            tests:
              - not_null